### PR TITLE
Allow binding to local port 0

### PR DESCRIPTION
**Pull request by anvilpete**
Add a `from_port` property that contains the actual local port used for the portforward.

### CODE REVIEW

**Comment by anvilpete** [comment]
@corka149 Hopefully self-explanatory, but let me know if you'd like to see any changes. This is a really nice Rust<->Python integration, thanks!

**Comment by corka149** [comment]
Hi @anvilpete awesome Idea! I would like to release this soon.

**Comment by corka149** [comment]
I wasn't aware how TcpListener is handling 0 as port. That's genius.

**Review by corka149 — APPROVED** [review]

**Comment by anvilpete** [comment]
Thanks for the quick merge! A release including this would be really useful.

**Comment by corka149** [comment]
Release is on the way 
https://github.com/pytogo/portforward/actions/runs/11408006531

**Comment by corka149** [comment]
Done

**Pull request merged**
