### PR TITLE
Ignore error when logger was already set

### PR DESCRIPTION
**Pull request by corka149**

### CODE REVIEW

**Comment by emranbm** [comment]
That's nice! when it's gonna be released?

**Comment by corka149** [comment]
I will wait until Friday for a response to the other open issue. If nothing happens I will release it this weekend.

**Comment by corka149** [comment]
@emranbm I nearly forgot to release the change. The MacOS and Linux version is published. And Windows will follow tomorrow.

**Comment by emranbm** [comment]
That's great. Thanks!

**Pull request merged**
